name: Naukri Profile Updater

on:
  workflow_dispatch:   # allows manual trigger from Actions tab
  schedule:
    - cron: "0 3 * * *"   # runs daily at 05:00 UTC (~10:30 AM IST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Naukri Automation
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: mvn -B compile exec:java -Dexec.mainClass="com.naukri.automation.automation.NaukriProfileUpdater"
